fix image/NavLink
Vladik-gif/Marketplace_Full_Stack pull request #63
Opened 2024-01-04 17:04 UTC by kuzen0211

- add propTypes
- add alt to image
- fix navLink

There were problems with merge because I didn't know that the development branch was protected

2024-01-05 00:26 UTC, Aleksey2892 requested changes
You have to fix some things before merging

2024-01-05 00:26 UTC, Aleksey2892 commented on frontend/src/pages/ThirdPage/ThirdPage.jsx
> +// import { useState } from 'react';
You should to delete commented import

2024-01-05 00:26 UTC, Aleksey2892 commented on frontend/src/pages/ThirdPage/ThirdPage.jsx
> +import { useLocation } from 'react-router-dom';
You should to move this import on first row

2024-01-05 00:35 UTC, Aleksey2892 commented on frontend/src/components/Filter/Desktop/FilterComputer/FilterComputer.jsx
> +    <>
there is also needed to delete empty fragment <>

2024-01-10 16:56 UTC, kuzen0211 commented on frontend/src/components/Filter/Mobile/FilterSmartphone/FilterSmartphone.jsx
> +      <>
done

2024-01-10 16:56 UTC, kuzen0211 commented on frontend/src/pages/ThirdPage/ThirdPage.jsx
> +import { useLocation } from 'react-router-dom';
done

2024-01-11 07:29 UTC, merged